plugins {
    id 'fml-loom' version '0.1'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "[很多库]" + project.archives_base_name
}

repositories {
    maven {
        name = "ModdedMITE"
        url = uri("https://maven.limingzxc.top/repository/maven-public/")
    }
}

configurations {
    fml
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    fml "com.github.MinecraftIsTooEasy:FishModLoader:3.4.2"
    implementation "com.github.MinecraftIsTooEasy:FishModLoader:3.4.2"

    // compile needed
    compileOnly "com.github.MinecraftIsTooEasy:ModMenu:10.1.1"
    compileOnly "com.github.MinecraftIsTooEasy:PinIn-Lib:1.6.0"

    // ModMenu need this when runClient
    localRuntime "com.github.MinecraftIsTooEasy:Gson:2.10.1"
    localRuntime "com.github.MinecraftIsTooEasy:ModernMITE:3.7.1"
    localRuntime "com.github.MinecraftIsTooEasy:OMMC:1.4.2"
    localRuntime "com.github.MinecraftIsTooEasy:Neodymium:1.1.1"
    localRuntime "com.github.MinecraftIsTooEasy:PinIn-Lib:1.6.0"
    localRuntime "com.github.MinecraftIsTooEasy:ModMenu:10.1.1"
    localRuntime "com.github.MinecraftIsTooEasy:ExtraGui:1.3.6"
    localRuntime "com.github.MinecraftIsTooEasy:RustedIronCore:1.5.0"
    localRuntime "com.github.MinecraftIsTooEasy:Waila:2.0.4"

}

def fmlResolvedFile = configurations.fml.files.iterator().next()

loom {
    accessWidenerPath = file("src/main/resources/manylib.accessWidener")
    mergedMinecraftJar()

    mods {
        "ManyLib" {
            sourceSet sourceSets.main
        }
    }
}

loom.setFML(fmlResolvedFile)
dependencies.add("mappings", loom.fmlMCPMappings())

processResources {
    inputs.property "version", project.version

    filesMatching("fml.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    inputs.property "archivesName", project.archives_base_name

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}

tasks.named('runClient', JavaExec).configure { exec ->
    def user = project.hasProperty('username') ? project.username : 'Dev'
    exec.setArgs(['--username', user, '--session', '0', '--width', '854', '--height', '480'])
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        maven {
            name = "ModdedMITE"
            url = uri("https://maven.limingzxc.top/repository/maven-releases/")
            credentials {
                // Read only from gradle.properties (user level, your gradle_home)
                username = project.findProperty("nexusUsername")
                password = project.findProperty("nexusPassword")
            }
        }
    }
}